import type { Artwork, Collection, ArtworkMedia, ArtworkSection } from "./types"

const USER_ID = "00000000-0000-0000-0000-000000000000"

export const placeholderCollections: Collection[] = [
  {
    id: "c1",
    title: "Landscapes of Memory",
    title_en: "",
    slug: "landscapes-of-memory",
    art_type: "painting",
    short_description: "A series exploring the landscapes that linger in our minds long after we leave them behind.",
    short_description_en: "",
    description: "This collection brings together paintings created over three years, each one drawn from a place I have visited and reimagined through the lens of memory. The colours shift, the edges blur, and what remains is the emotional imprint of a landscape rather than its literal form.",
    description_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sort_order: 0,
    is_published: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    user_id: USER_ID,
  },
  {
    id: "c2",
    title: "Silent Conversations",
    title_en: "",
    slug: "silent-conversations",
    art_type: "drawing",
    short_description: "Charcoal studies of intimate moments between people who share silence.",
    short_description_en: "",
    description: "In these drawings I explore the quiet exchanges that happen between people in shared spaces. A glance across a room, hands almost touching, the weight of presence without words.",
    description_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sort_order: 0,
    is_published: true,
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
    user_id: USER_ID,
  },
  {
    id: "c3",
    title: "Urban Solitude",
    title_en: "",
    slug: "urban-solitude",
    art_type: "photography",
    short_description: "Moments of solitude captured in the busiest corners of the city.",
    short_description_en: "",
    description: "Cities are full of people, yet loneliness persists in corners, on benches, through windows. This series finds those quiet pockets of isolation within the urban pulse.",
    description_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sort_order: 0,
    is_published: true,
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
    user_id: USER_ID,
  },
]

export const placeholderArtworks: Artwork[] = [
  // Paintings - in collection
  {
    id: "a1",
    title: "Morning Mist, Alentejo",
    title_en: "",
    slug: "morning-mist-alentejo",
    art_type: "painting",
    collection_id: "c1",
    short_description: "Oil on canvas capturing the golden dawn over cork oak fields.",
    short_description_en: "",
    description: "The mornings in Alentejo carry a particular quality of light that I have tried to hold onto in this painting. The mist lifts slowly from the earth, the cork oaks stand like sentinels, and for a few minutes everything is bathed in gold.",
    description_en: "",
    creation_date: "2023-06-15",
    dimensions: "80 x 60 cm",
    medium: "Oil on canvas",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 0,
    is_published: true,
    is_featured_home: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    user_id: USER_ID,
  },
  {
    id: "a2",
    title: "Atlantic Shore",
    title_en: "",
    slug: "atlantic-shore",
    art_type: "painting",
    collection_id: "c1",
    short_description: "The restless coast near Ericeira, rendered in deep blues and greens.",
    short_description_en: "",
    description: "The Atlantic coast is never still. This painting attempts to capture the energy and constant motion of the waves crashing against the cliffs near Ericeira.",
    description_en: "",
    creation_date: "2023-09-20",
    dimensions: "100 x 80 cm",
    medium: "Oil on canvas",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 1,
    is_published: true,
    is_featured_home: false,
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
    user_id: USER_ID,
  },
  // Painting - standalone
  {
    id: "a3",
    title: "Still Life with Lemons",
    title_en: "",
    slug: "still-life-with-lemons",
    art_type: "painting",
    collection_id: null,
    short_description: "A warm study of afternoon light falling across a kitchen table.",
    short_description_en: "",
    description: "Some of the most beautiful moments happen in the kitchen. The way afternoon sunlight catches the skin of a lemon, the gentle shadows cast by a ceramic bowl. This painting is a love letter to those everyday scenes.",
    description_en: "",
    creation_date: "2024-03-10",
    dimensions: "50 x 40 cm",
    medium: "Oil on linen",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 2,
    is_published: true,
    is_featured_home: true,
    created_at: "2024-03-10T00:00:00Z",
    updated_at: "2024-03-10T00:00:00Z",
    user_id: USER_ID,
  },
  // Drawings - in collection
  {
    id: "a4",
    title: "Two at a Table",
    title_en: "",
    slug: "two-at-a-table",
    art_type: "drawing",
    collection_id: "c2",
    short_description: "Charcoal on paper. Two figures sit across from each other, not speaking.",
    short_description_en: "",
    description: "There is a particular tension in shared silence. Two people who know each other deeply, sitting at a table, saying nothing. The charcoal captures the weight of what is left unsaid.",
    description_en: "",
    creation_date: "2024-01-20",
    dimensions: "42 x 30 cm",
    medium: "Charcoal on paper",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 0,
    is_published: true,
    is_featured_home: true,
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
    user_id: USER_ID,
  },
  {
    id: "a5",
    title: "Reading by the Window",
    title_en: "",
    slug: "reading-by-the-window",
    art_type: "drawing",
    collection_id: "c2",
    short_description: "A figure absorbed in a book, framed by window light.",
    short_description_en: "",
    description: "Light from the window wraps around the reader like a gentle embrace. The world outside fades; only the book and the body remain.",
    description_en: "",
    creation_date: "2024-02-14",
    dimensions: "42 x 30 cm",
    medium: "Charcoal and white chalk on toned paper",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 1,
    is_published: true,
    is_featured_home: false,
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
    user_id: USER_ID,
  },
  // Drawing standalone
  {
    id: "a6",
    title: "Hands Study IV",
    title_en: "",
    slug: "hands-study-iv",
    art_type: "drawing",
    collection_id: null,
    short_description: "Graphite study of aged hands at rest.",
    short_description_en: "",
    description: "Hands tell the story of a life lived. These hands belong to my grandmother, captured one afternoon as she rested in her garden chair.",
    description_en: "",
    creation_date: "2023-11-05",
    dimensions: "30 x 21 cm",
    medium: "Graphite on paper",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 2,
    is_published: true,
    is_featured_home: true,
    created_at: "2023-11-05T00:00:00Z",
    updated_at: "2023-11-05T00:00:00Z",
    user_id: USER_ID,
  },
  // Photography - in collection
  {
    id: "a7",
    title: "Metro, Line Blue",
    title_en: "",
    slug: "metro-line-blue",
    art_type: "photography",
    collection_id: "c3",
    short_description: "A lone commuter on the Lisbon metro, reflected in the tile wall.",
    short_description_en: "",
    description: "The Lisbon metro stations are works of art in themselves. Against the azulejo tiles, a solitary figure waits, their reflection merging with the patterns.",
    description_en: "",
    creation_date: "2024-04-02",
    dimensions: null,
    medium: "Digital photograph",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 0,
    is_published: true,
    is_featured_home: true,
    created_at: "2024-04-02T00:00:00Z",
    updated_at: "2024-04-02T00:00:00Z",
    user_id: USER_ID,
  },
  {
    id: "a8",
    title: "Park Bench, November",
    title_en: "",
    slug: "park-bench-november",
    art_type: "photography",
    collection_id: "c3",
    short_description: "Fallen leaves surround an empty bench in Estrela garden.",
    short_description_en: "",
    description: "November in Lisbon is gentle. The leaves fall softly, the benches empty, and the city takes a quiet breath before winter.",
    description_en: "",
    creation_date: "2023-11-18",
    dimensions: null,
    medium: "Film photograph, 35mm",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 1,
    is_published: true,
    is_featured_home: false,
    created_at: "2023-11-18T00:00:00Z",
    updated_at: "2023-11-18T00:00:00Z",
    user_id: USER_ID,
  },
  // Photography standalone
  {
    id: "a9",
    title: "Morning Market",
    title_en: "",
    slug: "morning-market",
    art_type: "photography",
    collection_id: null,
    short_description: "Early light spills over the stalls at Feira da Ladra.",
    short_description_en: "",
    description: "The flea market before the crowds arrive has a magic of its own. Vendors arranging their wares, the smell of coffee from a nearby stall, the first light touching the rooftops.",
    description_en: "",
    creation_date: "2024-05-12",
    dimensions: null,
    medium: "Digital photograph",
    medium_en: "",
    cover_image_url: "/placeholder-art.jpg",
    sale_url: null,
    sort_order: 2,
    is_published: true,
    is_featured_home: true,
    created_at: "2024-05-12T00:00:00Z",
    updated_at: "2024-05-12T00:00:00Z",
    user_id: USER_ID,
  },
  // Poems
  {
    id: "a10",
    title: "What the River Knows",
    title_en: "",
    slug: "what-the-river-knows",
    art_type: "poem",
    collection_id: null,
    short_description: "A meditation on time and flow, written beside the Tagus.",
    short_description_en: "",
    description: "The river does not hurry.\nIt carries what it carries\nwithout complaint or explanation.\nThe boats come and go,\nthe bridges hold their breath,\nand still the water moves\ntoward the sea\nwith a patience I am trying to learn.",
    description_en: "",
    creation_date: "2024-06-01",
    dimensions: null,
    medium: null,
    medium_en: null,
    cover_image_url: null,
    sale_url: null,
    sort_order: 0,
    is_published: true,
    is_featured_home: true,
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2024-06-01T00:00:00Z",
    user_id: USER_ID,
  },
  {
    id: "a11",
    title: "Saudade",
    title_en: "",
    slug: "saudade",
    art_type: "poem",
    collection_id: null,
    short_description: "On the untranslatable feeling of longing for something you still have.",
    short_description_en: "",
    description: "There is a word in my language\nthat other languages borrow but never quite hold.\nIt lives in the space between\nhaving and remembering,\nbetween the touch and the echo of a touch.\nI carry it like a second heartbeat.",
    description_en: "",
    creation_date: "2024-07-15",
    dimensions: null,
    medium: null,
    medium_en: null,
    cover_image_url: null,
    sale_url: null,
    sort_order: 1,
    is_published: true,
    is_featured_home: true,
    created_at: "2024-07-15T00:00:00Z",
    updated_at: "2024-07-15T00:00:00Z",
    user_id: USER_ID,
  },
  {
    id: "a12",
    title: "Kitchen Song",
    title_en: "",
    slug: "kitchen-song",
    art_type: "poem",
    collection_id: null,
    short_description: "The music of ordinary mornings, cups and spoons and sunlight.",
    short_description_en: "",
    description: "The kettle sings its one note.\nA spoon taps twice against a cup.\nOutside, the neighbour's radio\nleaks a fado through the wall.\nThis is the morning symphony,\nunrehearsed,\nperfect.",
    description_en: "",
    creation_date: "2024-08-20",
    dimensions: null,
    medium: null,
    medium_en: null,
    cover_image_url: null,
    sale_url: null,
    sort_order: 2,
    is_published: true,
    is_featured_home: false,
    created_at: "2024-08-20T00:00:00Z",
    updated_at: "2024-08-20T00:00:00Z",
    user_id: USER_ID,
  },
]

export const placeholderMedia: ArtworkMedia[] = [
  {
    id: "m1",
    artwork_id: "a1",
    media_url: "/placeholder-art.jpg",
    media_type: "image",
    caption: "Detail of the morning light on the cork oaks",
    sort_order: 0,
    created_at: "2024-08-20T00:00:00Z",
    file_name: "test-name1.jpg",
    file_size: 1234567,
  },
  {
    id: "m2",
    artwork_id: "a1",
    media_url: "/placeholder-art.jpg",
    media_type: "image",
    caption: "Work in progress, studio shot",
    sort_order: 1,
    created_at: "2024-08-20T00:00:00Z",
    file_name: "test-name2.jpg",
    file_size: 1234567,
  },
]

export const placeholderSections: ArtworkSection[] = [
  {
    id: "s1",
    artwork_id: "a1",
    title: "Process",
    content: "This painting began as a plein air sketch during a visit to the Alentejo region in the summer of 2023. The final work was completed in the studio over several weeks, layering glazes to achieve the luminous quality of the original morning light.",
    sort_order: 0,
    created_at: "2024-08-20T00:00:00Z",
    updated_at: "2024-08-20T00:00:00Z",
  },
]
